title: KELE 教程

description: Knowledge Equations based on Logical Engine
baseurl: "/zh"

includes_dir: ../_includes
layouts_dir: ../_layouts
sass:
  load_paths:
    - ../_sass

gh_edit_source: "zh"

exclude:
  - en

aux_links:
  English:
    - "/en/"

aux_links_new_tab: true
