title: KELE Tutorial (EN)
description: Knowledge Equations based on Logical Engine
baseurl: "/en"

includes_dir: ../_includes
layouts_dir: ../_layouts
sass:
  load_paths:
    - ../_sass

gh_edit_source: "en"

exclude:
  - zh

aux_links:
  中文:
    - "/zh/"

aux_links_new_tab: true
