title: KELE Tutorial
description: Knowledge Equations based on Logical Engine
theme: just-the-docs

url: https://msg-bq.github.io

aux_links:
  KELE on Github: https://github.com/msg-bq/AL_inference_engine
